# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest and lint

on:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev

    - name: Lint
      env:
        CHECK: true
      run: |
        pipenv run ./bin/lint

    # - name: Test with pytest
    #   env:
    #     TELEGRAM_USERNAME: hCaptchaTestBot
    #     TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    #     HCAPTCHA_SECRET: "fake"
    #     HCAPTCHA_SITE_KEY: "fake"
    #   run: |
    #     pipenv run python3 -m pytest

    - name: PyTest w/ Coverage
      env:
        TELEGRAM_USERNAME: hCaptchaTestBot
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        HCAPTCHA_SECRET: "fake"
        HCAPTCHA_SITE_KEY: "fake"
      run: |
        pipenv run coverage run --include="app/*" -m pytest
